version: '3.8'

services:
  api-gateway:
    build: ./api-gateway
    volumes:
      - ./api-gateway:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

  sidecar:
    build: ./sidecar
    volumes:
      - ./sidecar:/sidecar
    depends_on:
      - api-gateway
